spring:
  application:
    name: springcloud-video-system
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8760/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: springcloud-video-system
asd: asd
